config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "application#index"

    resources :projects, only: [:new, :create, :destroy]
    resources :users
  end

  devise_for :users

  root 'projects#index'

  resources :projects, only: [:index, :show, :edit, :update] do
  	resources :tickets
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tickets, dependent: :delete_all
	
	validates :name, presence: true
	#validates :description, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User"

  validates :title, presence: true
  validates :description, presence: true, length: {minimum: 10}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!

  def index
  end

  private

  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that."
	  end 
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
	def new
		@project = Project.new 
	end

	def create
	  @project = Project.new(project_params)

	  if @project.save
	    flash[:hola] = "Project has been created."
	    redirect_to @project
	  else
	    flash[:alert] = "Project has not been created."
    	render "new"
	  end 
	end

	def destroy
	  @project = Project.find(params[:id])
	  @project.destroy
	  flash[:notice] = "Project has been destroyed."
	  redirect_to @project
	end

	private
	  	def project_params
	   	  params.require(:project).permit(:name, :description)
	    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
  	@users = User.order(:email)
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  	  flash[:notice] = "User has been created."
  	  redirect_to admin_users_path
  	else
  	  flash[:alert] = "User has not been created."
  	  render "new"
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update]

	def index
		@projects = Project.all
	end

	def show
	end

	def edit
	end

	def update
	  if @project.update(project_params)
	    flash[:notice] = "Project has been updated."
	    redirect_to @project
	  else
	    flash[:alert] = "Project has not been updated."
	    render "edit"
	  end
	end

	private
	  	def project_params
	   	  params.require(:project).permit(:name, :description)
	    end

	    def set_project
    	  @project = Project.find(params[:id])
  		  rescue ActiveRecord::RecordNotFound
    	    flash[:alert] = "The project you were looking for could not be found."
    	    redirect_to projects_path
  		end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.author = current_user
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been created."
      render "new"
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Project has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Project has not been updated."
      render "edit"
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Project has been destroyed."
    redirect_to @project
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_ticket
      @ticket = @project.tickets.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:title, :description)
    end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
	end
  end
end

def only_admin &block
  block.call if current_user.try(:admin?)
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/application/index.html.erb
<div class="row" id="admin">
  <div class="col-md-9">
    <header>
      <h1>Admin Lounge</h1>
	</header>
	<p>Welcome to Ticketee's Admin Lounge. Please enjoy your stay.</p>
  </div>
  <div class="col-md-3">
    <h2>Admin Links</h2>
    <ul class="nav nav-stacked">
      <li><%= link_to "Users", admin_users_path %></li>
    </ul>
  </div>
</div>

app/views/admin/projects/_form.html.erb
<%= form_for([:admin, @project]) do |f| %>
  <% if @project.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@project.errors.count, "error") %>
       prohibited this project from being saved:</h2>
     <ul>
     <% @project.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
   <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
</p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/admin/projects/new.html.erb
<h2>New Project</h2>

<%= render "form" %>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
<section class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>
</section>
 
<section class="form-group">
  <%= f.label :password %>
  <%= f.text_field :password, class: "form-control" %>
</section>
  
<section class="form-group">
  <%= f.button :submit, class: "btn btn-primary" %>
</section>
<% end %>

app/views/admin/users/index.html.erb
<header>
  <h1>Users</h1>
  <ul class="actions">
	<li><%= link_to "New User", new_admin_user_path, class: "new" %></li> 
  </ul>
  <ul>
  	<% @users.each do |user| %>
  		<li>
  			<%= link_to user.email, [:admin, user] %>
  		</li>
  	<%end%>
  </ul>
</header>

app/views/admin/users/new.html.erb
<header>
	<h1>New User</h1>
</header>

 <%= render "form" %>

app/views/layouts/application.html.erb
<html>
<head>
<title>
  <% if content_for?(:title) %>
    <%= yield(:title) %>
  <% else %>
    Ticketee
  <% end %>
</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #F2F2F2;">
  <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <section class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header"><%= link_to 'Ticketee', projects_path, class: 'navbar-brand' %></div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-right">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if current_page?("/") %>">
          <%= link_to "Home", root_path %>
        </li>
        <% only_admin do %>
          <li class="<%= "active" if current_page?("/admin") %>">
            <%= link_to "Admin", admin_root_path %>
          </li>
        <%end%>
        <% unless user_signed_in? %>
          <li><%= link_to "Registrate", new_user_registration_path %></li>
          <li><%= link_to "Inicia session", new_user_session_path %></li>
        <%end%>
          <% if user_signed_in? %> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Editar cuenta", edit_user_registration_path %></li>
            <li><%= link_to "Cerrar session", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <%end%>
      </ul>
      </section>
  </div><!-- /.container-fluid -->
</nav>

<section class="container" id="container-body">
<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<% only_admin do %>  
  <%= link_to "New Project", new_admin_project_path %>
<%end%>

<%= yield %>
</section>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@project.errors.count, "error") %>
       prohibited this project from being saved:</h2>
     <ul>
     <% @project.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
   <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
</p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>

<%= render "form" %>

app/views/projects/index.html.erb
<p><%= params[:project] %></p>

<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %></h2>
<p><%= @project.description %></p>
<%= link_to "Edit Project", edit_project_path(@project) %>
<% only_admin do %>
  <%= link_to "Delete Project", admin_project_path(@project), method: :delete, data: { confirm:"Are you sure you want to delete this project?"} %>
<%end%>
<%= link_to "New Ticket", new_project_ticket_path(@project), class: "btn-primary"%>

<ul id="tickets">
  <% @project.tickets.each do |ticket| %>
    <li>
    	#<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <%end%>
</ul>

app/views/tickets/_form.html.erb
<%= form_for [@project,@ticket] do |f| %>
  <% if @ticket.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@ticket.errors.count, "error") %>
     prohibited this ticket from being saved:</h2>
     <ul>
     <% @ticket.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
  <% end %>
  <p>
    <%= f.label :title%> <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %> <br>
    <%= f.text_field :description %>
  </p>
  <%= f.submit %>
<%end%>

app/views/tickets/edit.html.erb
<h2>Editar Ticket "<%= @ticket.title %>"</h2>
<%= render 'form' %>

app/views/tickets/new.html.erb
<h2>Nuevo Ticket</h2>

<%= render "form" %>

app/views/tickets/show.html.erb
<div id='ticket'>
  <h2><%= @ticket.title %></h2>
  <%= simple_format(@ticket.description) %>
  <%= link_to 'Editar', edit_project_ticket_path(@project, @ticket) %>
  <%= link_to "Delete ticket", [@project, @ticket], method: :delete, data: { confirm:"Are you sure you want to delete this project?"} %>
</div>

<table id="attributes">
   <tr>
     <th>Author:</th>
     <td><%= @ticket.author.email %></td>
   </tr>
   <tr>
     <th>Created:</th>
     <td><%= time_ago_in_words(@ticket.created_at) %> ago</td>
   </tr>
</table>